### ISSUE TITLE
Source missing for Mara [mec]

### ISSUE THREAD

**Issue by HedvigS** [clld/nts#1]
There is no source indicated for any data point for Mara [mec], not in the online version nor in my sheet that I have from Ger and Michael. It should be Heath (1981), but well. It is not indicated.

Heath, Jeffrey. 1981. Basic materials in Mara: grammar, texts and dictionary. Pacific Linguistics, Series C-60. Department of Linguistics. Research School of Pacific and Asian Studies: The Australian National University.

**Comment by d97hah** [comment]
Thanks, will fix that when we get to the NTS cleanup

2015-07-07 8:45 GMT+02:00 Hedvig Skirgård notifications@github.com:
